#import <Foundation/Foundation.h>
#import "OAIApi.h"

/**
* Location API
* Geolocation, Geocoding and Maps
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAITimezoneApi: NSObject <OAIApi>

extern NSString* kOAITimezoneApiErrorDomain;
extern NSInteger kOAITimezoneApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// timezone
/// The Unwired Labs TimeZone API provides time offset data for locations on the surface of the earth.
///
/// @param lat lattitude of the location
/// @param lon longitude of location
/// 
///  code:200 message:"timezone response"
///
/// @return NSObject*
-(NSURLSessionTask*) timezoneWithLat: (NSNumber*) lat
    lon: (NSNumber*) lon
    completionHandler: (void (^)(NSObject* output, NSError* error)) handler;



@end
