/**
 * Location API
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIAddress_details_schema.h
 *
 * The API only returns components that have valid values for a location. Component town is normalized to city to make things simple
 */

#ifndef OAIAddress_details_schema_H_
#define OAIAddress_details_schema_H_

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIAddress_details_schema: public OAIObject {
public:
    OAIAddress_details_schema();
    OAIAddress_details_schema(QString json);
    ~OAIAddress_details_schema();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIAddress_details_schema* fromJson(QString jsonString) override;

    QString* getArea();
    void setArea(QString* area);

    QString* getLocality();
    void setLocality(QString* locality);

    QString* getDistrict();
    void setDistrict(QString* district);

    QString* getCounty();
    void setCounty(QString* county);

    QString* getCity();
    void setCity(QString* city);

    QString* getState();
    void setState(QString* state);

    QString* getCountry();
    void setCountry(QString* country);

    QString* getCountryCode();
    void setCountryCode(QString* country_code);

    QString* getPostalCode();
    void setPostalCode(QString* postal_code);


    virtual bool isSet() override;

private:
    QString* area;
    bool m_area_isSet;

    QString* locality;
    bool m_locality_isSet;

    QString* district;
    bool m_district_isSet;

    QString* county;
    bool m_county_isSet;

    QString* city;
    bool m_city_isSet;

    QString* state;
    bool m_state_isSet;

    QString* country;
    bool m_country_isSet;

    QString* country_code;
    bool m_country_code_isSet;

    QString* postal_code;
    bool m_postal_code_isSet;

};

}

#endif /* OAIAddress_details_schema_H_ */
