/**
 * Location API
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIBalance_response_schema.h
 *
 * 
 */

#ifndef OAIBalance_response_schema_H_
#define OAIBalance_response_schema_H_

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIBalance_response_schema: public OAIObject {
public:
    OAIBalance_response_schema();
    OAIBalance_response_schema(QString json);
    ~OAIBalance_response_schema();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIBalance_response_schema* fromJson(QString jsonString) override;

    QString* getStatus();
    void setStatus(QString* status);

    qint64 getBalanceGeolocation();
    void setBalanceGeolocation(qint64 balance_geolocation);

    qint64 getBalanceGeocoding();
    void setBalanceGeocoding(qint64 balance_geocoding);


    virtual bool isSet() override;

private:
    QString* status;
    bool m_status_isSet;

    qint64 balance_geolocation;
    bool m_balance_geolocation_isSet;

    qint64 balance_geocoding;
    bool m_balance_geocoding_isSet;

};

}

#endif /* OAIBalance_response_schema_H_ */
