/**
 * Location API
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIBt_schema.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIBt_schema::OAIBt_schema(QString json) {
    init();
    this->fromJson(json);
}

OAIBt_schema::OAIBt_schema() {
    init();
}

OAIBt_schema::~OAIBt_schema() {
    this->cleanup();
}

void
OAIBt_schema::init() {
}

void
OAIBt_schema::cleanup() {
}

OAIBt_schema*
OAIBt_schema::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIBt_schema::fromJsonObject(QJsonObject pJson) {
}

QString
OAIBt_schema::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIBt_schema::asJsonObject() {
    QJsonObject obj;

    return obj;
}


bool
OAIBt_schema::isSet(){
    bool isObjectUpdated = false;
    do{
    }while(false);
    return isObjectUpdated;
}
}

