/**
 * Location API
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAICell_schema.h
 *
 * You can send 1 to 7 cell ID objects. If your device supports scanning for more than 7 cell objects, reach out to us and we’ll increase this limit on your account. The first cell object has to be that of the serving cell, i.e. the tower the device is connected to. The others are neighbouring cell objects that are visible to the device. Except lac and cid all other parameters mentioned below are optional. Parameters vary depending on the radio type. Supported radio types and their corresponding parameters are
 */

#ifndef OAICell_schema_H_
#define OAICell_schema_H_

#include <QJsonObject>


#include "OAIRadio_schema.h"

#include "OAIObject.h"

namespace OpenAPI {

class OAICell_schema: public OAIObject {
public:
    OAICell_schema();
    OAICell_schema(QString json);
    ~OAICell_schema();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAICell_schema* fromJson(QString jsonString) override;

    qint64 getLac();
    void setLac(qint64 lac);

    qint64 getCid();
    void setCid(qint64 cid);

    OAIRadio_schema* getRadio();
    void setRadio(OAIRadio_schema* radio);

    qint64 getMcc();
    void setMcc(qint64 mcc);

    qint64 getMnc();
    void setMnc(qint64 mnc);

    qint64 getSignal();
    void setSignal(qint64 signal);

    qint64 getPsc();
    void setPsc(qint64 psc);

    qint64 getAsu();
    void setAsu(qint64 asu);

    qint64 getTa();
    void setTa(qint64 ta);


    virtual bool isSet() override;

private:
    qint64 lac;
    bool m_lac_isSet;

    qint64 cid;
    bool m_cid_isSet;

    OAIRadio_schema* radio;
    bool m_radio_isSet;

    qint64 mcc;
    bool m_mcc_isSet;

    qint64 mnc;
    bool m_mnc_isSet;

    qint64 signal;
    bool m_signal_isSet;

    qint64 psc;
    bool m_psc_isSet;

    qint64 asu;
    bool m_asu_isSet;

    qint64 ta;
    bool m_ta_isSet;

};

}

#endif /* OAICell_schema_H_ */
