/**
 * Location API
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAIError_schema.h
 *
 * 
 */

#ifndef OAIError_schema_H_
#define OAIError_schema_H_

#include <QJsonObject>


#include <QString>

#include "OAIObject.h"

namespace OpenAPI {

class OAIError_schema: public OAIObject {
public:
    OAIError_schema();
    OAIError_schema(QString json);
    ~OAIError_schema();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAIError_schema* fromJson(QString jsonString) override;

    QString* getStatus();
    void setStatus(QString* status);

    QString* getMessage();
    void setMessage(QString* message);


    virtual bool isSet() override;

private:
    QString* status;
    bool m_status_isSet;

    QString* message;
    bool m_message_isSet;

};

}

#endif /* OAIError_schema_H_ */
