/**
 * Location API
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include "OAIGeolocation_error_schema.h"

#include "OAIHelpers.h"

#include <QJsonDocument>
#include <QJsonArray>
#include <QObject>
#include <QDebug>

namespace OpenAPI {

OAIGeolocation_error_schema::OAIGeolocation_error_schema(QString json) {
    init();
    this->fromJson(json);
}

OAIGeolocation_error_schema::OAIGeolocation_error_schema() {
    init();
}

OAIGeolocation_error_schema::~OAIGeolocation_error_schema() {
    this->cleanup();
}

void
OAIGeolocation_error_schema::init() {
    status = new QString("");
    m_status_isSet = false;
    message = new QString("");
    m_message_isSet = false;
    balance = 0L;
    m_balance_isSet = false;
}

void
OAIGeolocation_error_schema::cleanup() {
    if(status != nullptr) { 
        delete status;
    }
    if(message != nullptr) { 
        delete message;
    }

}

OAIGeolocation_error_schema*
OAIGeolocation_error_schema::fromJson(QString json) {
    QByteArray array (json.toStdString().c_str());
    QJsonDocument doc = QJsonDocument::fromJson(array);
    QJsonObject jsonObject = doc.object();
    this->fromJsonObject(jsonObject);
    return this;
}

void
OAIGeolocation_error_schema::fromJsonObject(QJsonObject pJson) {
    ::OpenAPI::setValue(&status, pJson["status"], "QString", "QString");
    
    ::OpenAPI::setValue(&message, pJson["message"], "QString", "QString");
    
    ::OpenAPI::setValue(&balance, pJson["balance"], "qint64", "");
    
}

QString
OAIGeolocation_error_schema::asJson ()
{
    QJsonObject obj = this->asJsonObject();
    QJsonDocument doc(obj);
    QByteArray bytes = doc.toJson();
    return QString(bytes);
}

QJsonObject
OAIGeolocation_error_schema::asJsonObject() {
    QJsonObject obj;
    if(status != nullptr && *status != QString("")){
        toJsonValue(QString("status"), status, obj, QString("QString"));
    }
    if(message != nullptr && *message != QString("")){
        toJsonValue(QString("message"), message, obj, QString("QString"));
    }
    if(m_balance_isSet){
        obj.insert("balance", QJsonValue(balance));
    }

    return obj;
}

QString*
OAIGeolocation_error_schema::getStatus() {
    return status;
}
void
OAIGeolocation_error_schema::setStatus(QString* status) {
    this->status = status;
    this->m_status_isSet = true;
}

QString*
OAIGeolocation_error_schema::getMessage() {
    return message;
}
void
OAIGeolocation_error_schema::setMessage(QString* message) {
    this->message = message;
    this->m_message_isSet = true;
}

qint64
OAIGeolocation_error_schema::getBalance() {
    return balance;
}
void
OAIGeolocation_error_schema::setBalance(qint64 balance) {
    this->balance = balance;
    this->m_balance_isSet = true;
}


bool
OAIGeolocation_error_schema::isSet(){
    bool isObjectUpdated = false;
    do{
        if(status != nullptr && *status != QString("")){ isObjectUpdated = true; break;}
        if(message != nullptr && *message != QString("")){ isObjectUpdated = true; break;}
        if(m_balance_isSet){ isObjectUpdated = true; break;}
    }while(false);
    return isObjectUpdated;
}
}

