/**
 * Location API
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * OAILacf_schema.h
 *
 * Enable LAC fallback. If we are unable to locate a cell, we will return an approzimate location based on nearby cells in our database.
 */

#ifndef OAILacf_schema_H_
#define OAILacf_schema_H_

#include <QJsonObject>



#include "OAIObject.h"

namespace OpenAPI {

class OAILacf_schema: public OAIObject {
public:
    OAILacf_schema();
    OAILacf_schema(QString json);
    ~OAILacf_schema();
    void init();
    void cleanup();

    QString asJson () override;
    QJsonObject asJsonObject() override;
    void fromJsonObject(QJsonObject json) override;
    OAILacf_schema* fromJson(QString jsonString) override;


    virtual bool isSet() override;

private:
};

}

#endif /* OAILacf_schema_H_ */
