/**
 * Location API
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef _OAI_OAISEARCHApi_H_
#define _OAI_OAISEARCHApi_H_

#include "OAIHttpRequest.h"

#include "OAIObject.h"
#include <QString>

#include <QObject>

namespace OpenAPI {

class OAISEARCHApi: public QObject {
    Q_OBJECT

public:
    OAISEARCHApi();
    OAISEARCHApi(QString host, QString basePath);
    ~OAISEARCHApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void search(QString* q, QString* viewbox, qint64 limit, QString* accept_language, QString* countrycodes);
    
private:
    void searchCallback (OAIHttpRequestWorker * worker);
    
signals:
    void searchSignal(OAIObject* summary);
    
    void searchSignalE(OAIObject* summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void searchSignalEFull(OAIHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
