/**
 * Location API
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model


case class TimezoneResponseSchema (
  // If the request is successful, ok is returned. Otherwise error is returned
  status: Option[String] = None,
  // Balance left in the account
  balance: Option[Long] = None,
  timezone: Option[TimezoneSchema] = None
)

