/**
 * Location API
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.model


case class TimezoneSchema (
  // Short name of the Timezone
  shortName: Option[String] = None,
  // The offset from UTC (in seconds) for the given location. Considers DST savings.
  offsetSec: Option[Number] = None,
  // Represents whether the zone currently observing DST or not
  nowInDst: Option[String] = None,
  // Timezone name of the Location
  name: Option[String] = None
)

