=begin comment

Location API

Geolocation, Geocoding and Maps

OpenAPI spec version: 2.0.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::REVERSEApi;

require 5.6.0;
use strict;
use warnings;
use utf8; 
use Exporter;
use Carp qw( croak );
use Log::Any qw($log);

use WWW::OpenAPIClient::ApiClient;

use base "Class::Data::Inheritable";

__PACKAGE__->mk_classdata('method_documentation' => {});

sub new {
    my $class = shift;
    my $api_client;

    if ($_[0] && ref $_[0] && ref $_[0] eq 'WWW::OpenAPIClient::ApiClient' ) {
        $api_client = $_[0];
    } else {
        $api_client = WWW::OpenAPIClient::ApiClient->new(@_);
    }

    bless { api_client => $api_client }, $class;

}


#
# reverse
#
# Reverse Geocoding
# 
# @param double $lat Latitude of the location to generate an address for. (required)
# @param double $lon Longitude of the location to generate an address for. (required)
# @param int $zoom Zoom value lies between 0-18. Level of detail required where 0 is country and 18 is house/building (optional)
# @param string $accept_language Preferred language order for showing search results, overrides the value specified in the Accept-Language HTTP header. Defaults to en. To use native language for the response when available, use accept-language&#x3D;native (optional)
{
    my $params = {
    'lat' => {
        data_type => 'double',
        description => 'Latitude of the location to generate an address for.',
        required => '1',
    },
    'lon' => {
        data_type => 'double',
        description => 'Longitude of the location to generate an address for.',
        required => '1',
    },
    'zoom' => {
        data_type => 'int',
        description => 'Zoom value lies between 0-18. Level of detail required where 0 is country and 18 is house/building',
        required => '0',
    },
    'accept_language' => {
        data_type => 'string',
        description => 'Preferred language order for showing search results, overrides the value specified in the Accept-Language HTTP header. Defaults to en. To use native language for the response when available, use accept-language&#x3D;native',
        required => '0',
    },
    };
    __PACKAGE__->method_documentation->{ 'reverse' } = { 
    	summary => 'Reverse Geocoding',
        params => $params,
        returns => 'object',
        };
}
# @return object
#
sub reverse {
    my ($self, %args) = @_;

    # verify the required parameter 'lat' is set
    unless (exists $args{'lat'}) {
      croak("Missing the required parameter 'lat' when calling reverse");
    }

    # verify the required parameter 'lon' is set
    unless (exists $args{'lon'}) {
      croak("Missing the required parameter 'lon' when calling reverse");
    }

    # parse inputs
    my $_resource_path = '/reverse.php';

    my $_method = 'GET';
    my $query_params = {};
    my $header_params = {};
    my $form_params = {};

    # 'Accept' and 'Content-Type' header
    my $_header_accept = $self->{api_client}->select_header_accept('application/json');
    if ($_header_accept) {
        $header_params->{'Accept'} = $_header_accept;
    }
    $header_params->{'Content-Type'} = $self->{api_client}->select_header_content_type();

    # query params
    if ( exists $args{'lat'}) {
        $query_params->{'lat'} = $self->{api_client}->to_query_value($args{'lat'});
    }

    # query params
    if ( exists $args{'lon'}) {
        $query_params->{'lon'} = $self->{api_client}->to_query_value($args{'lon'});
    }

    # query params
    if ( exists $args{'zoom'}) {
        $query_params->{'zoom'} = $self->{api_client}->to_query_value($args{'zoom'});
    }

    # query params
    if ( exists $args{'accept_language'}) {
        $query_params->{'accept-language'} = $self->{api_client}->to_query_value($args{'accept_language'});
    }

    my $_body_data;
    # authentication setting, if any
    my $auth_settings = [qw(token )];

    # make the API Call
    my $response = $self->{api_client}->call_api($_resource_path, $_method,
                                           $query_params, $form_params,
                                           $header_params, $_body_data, $auth_settings);
    if (!$response) {
        return;
    }
    my $_response_object = $self->{api_client}->deserialize('object', $response);
    return $_response_object;
}

1;
