/*
 * Location API
 *
 * Geolocation, Geocoding and Maps
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package unwired

// Timezone object found for the location.
type TimezoneSchema struct {
	// Short name of the Timezone
	ShortName string `json:"short_name,omitempty"`
	// The offset from UTC (in seconds) for the given location. Considers DST savings.
	OffsetSec float32 `json:"offset_sec,omitempty"`
	// Represents whether the zone currently observing DST or not
	NowInDst string `json:"now_in_dst,omitempty"`
	// Timezone name of the Location
	Name string `json:"name,omitempty"`
}
