/*
 * Location API
 *
 * Geolocation, Geocoding and Maps
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package unwired

// You can send 1 to 7 cell ID objects. If your device supports scanning for more than 7 cell objects, reach out to us and we’ll increase this limit on your account. The first cell object has to be that of the serving cell, i.e. the tower the device is connected to. The others are neighbouring cell objects that are visible to the device. Except lac and cid all other parameters mentioned below are optional. Parameters vary depending on the radio type. Supported radio types and their corresponding parameters are
type CellSchema struct {
	// the Location Area Code of your operator’s network.
	Lac int64 `json:"lac,omitempty"`
	// Cell ID
	Cid int64 `json:"cid,omitempty"`
	Radio RadioSchema `json:"radio,omitempty"`
	// \"Mobile Country Code of your operator’s network represented by an integer (Optional). Range: 0 to 999.\"
	Mcc int64 `json:"mcc,omitempty"`
	// Mobile Network Code of your operator’s network represented by an integer (Optional). Range: 0 to 999. On CDMA, provide the System ID or SID, with range: 1 to 32767.
	Mnc int64 `json:"mnc,omitempty"`
	// Signal Strength (RSSI)
	Signal int64 `json:"signal,omitempty"`
	// Primary Scrambling Code
	Psc int64 `json:"psc,omitempty"`
	// Arbitrary Strength Unit
	Asu int64 `json:"asu,omitempty"`
	// Timing Advance
	Ta int64 `json:"ta,omitempty"`
}
