/*
 * Location API
 *
 * Geolocation, Geocoding and Maps
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package unwired
// IpfSchema : Enable IP address fallback. Specify IP address of the device in the “ip” field if it’s different from the device making the API call.
type IpfSchema int32

// List of ipf_schema
const (
	_0 IpfSchema = "0"
	_1 IpfSchema = "1"
)