/*
 * Location API
 *
 * Geolocation, Geocoding and Maps
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package unwired
// LacfSchema : Enable LAC fallback. If we are unable to locate a cell, we will return an approzimate location based on nearby cells in our database.
type LacfSchema int32

// List of lacf_schema
const (
	_0 LacfSchema = "0"
	_1 LacfSchema = "1"
	_2 LacfSchema = "2"
)