/*
 * Location API
 *
 * Geolocation, Geocoding and Maps
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package unwired
// BtSchema : Specify level of strictness to apply to Borders
type BtSchema int32

// List of bt_schema
const (
	_0 BtSchema = "0"
	_1 BtSchema = "1"
	_2 BtSchema = "2"
)