/*
 * Location API
 *
 * Geolocation, Geocoding and Maps
 *
 * API version: 2.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package unwired

// You can send a minimum of 2 and a maximum of 15 WiFi objects in 1 request. If WiFi is not available, wifi object can be omitted all together. In accordance with our industry’s privacy standards we require a minimum of 2 valid nearby Access Points to be sent. If your use-case allows only 1 AP, reach out to us.
type WifiSchema struct {
	// Basic Service Set Identifier or MAC address of the Access Point. Typical format of a MAC address is xx-xx-xx-xx-xx-xx. However, the delimiter can be any of these when sent to the API: : or - or .
	Bssid string `json:"bssid,omitempty"`
	// Channel the WiFi network is operating in (optional)
	Channel int64 `json:"channel,omitempty"`
	// Frequency the WiFi network is operating in (MHz) (optional)
	Frequency int64 `json:"frequency,omitempty"`
	// Signal Strength (RSSI)
	Signal int64 `json:"signal,omitempty"`
	// The current signal to noise ratio, measured in dB (optional)
	SignalToNoiseRatio int64 `json:"signalToNoiseRatio,omitempty"`
}
