=begin
#Location API

#Geolocation, Geocoding and Maps

OpenAPI spec version: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for unwiredClient::AllSchema
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AllSchema' do
  before do
    # run before each test
    @instance = unwiredClient::AllSchema.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AllSchema' do
    it 'should create an instance of AllSchema' do
      expect(@instance).to be_instance_of(unwiredClient::AllSchema)
    end
  end
end
