=begin comment

Location API

Geolocation, Geocoding and Maps

OpenAPI spec version: 2.0.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
package WWW::OpenAPIClient::Object::GeolocationResponseSchema;

require 5.6.0;
use strict;
use warnings;
use utf8;
use JSON qw(decode_json);
use Data::Dumper;
use Module::Runtime qw(use_module);
use Log::Any qw($log);
use Date::Parse;
use DateTime;

use WWW::OpenAPIClient::Object::AddressDetailsSchema;
use WWW::OpenAPIClient::Object::FallbackSchema;

use base ("Class::Accessor", "Class::Data::Inheritable");


#
#The response will be a JSON object.
#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech). Do not edit the class manually.
# REF: https://openapi-generator.tech
#

=begin comment

Location API

Geolocation, Geocoding and Maps

OpenAPI spec version: 2.0.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# Do not edit the class manually.
# Ref: https://openapi-generator.tech
#
__PACKAGE__->mk_classdata('attribute_map' => {});
__PACKAGE__->mk_classdata('openapi_types' => {});
__PACKAGE__->mk_classdata('method_documentation' => {}); 
__PACKAGE__->mk_classdata('class_documentation' => {});

# new object
sub new { 
    my ($class, %args) = @_; 

	my $self = bless {}, $class;
	
	foreach my $attribute (keys %{$class->attribute_map}) {
		my $args_key = $class->attribute_map->{$attribute};
		$self->$attribute( $args{ $args_key } );
	}
	
	return $self;
}  

# return perl hash
sub to_hash {
    return decode_json(JSON->new->convert_blessed->encode( shift ));
}

# used by JSON for serialization
sub TO_JSON { 
    my $self = shift;
    my $_data = {};
    foreach my $_key (keys %{$self->attribute_map}) {
        if (defined $self->{$_key}) {
            $_data->{$self->attribute_map->{$_key}} = $self->{$_key};
        }
    }
    return $_data;
}

# from Perl hashref
sub from_hash {
    my ($self, $hash) = @_;

    # loop through attributes and use openapi_types to deserialize the data
    while ( my ($_key, $_type) = each %{$self->openapi_types} ) {
    	my $_json_attribute = $self->attribute_map->{$_key}; 
        if ($_type =~ /^array\[/i) { # array
            my $_subclass = substr($_type, 6, -1);
            my @_array = ();
            foreach my $_element (@{$hash->{$_json_attribute}}) {
                push @_array, $self->_deserialize($_subclass, $_element);
            }
            $self->{$_key} = \@_array;
        } elsif (exists $hash->{$_json_attribute}) { #hash(model), primitive, datetime
            $self->{$_key} = $self->_deserialize($_type, $hash->{$_json_attribute});
        } else {
        	$log->debugf("Warning: %s (%s) does not exist in input hash\n", $_key, $_json_attribute);
        }
    }
  
    return $self;
}

# deserialize non-array data
sub _deserialize {
    my ($self, $type, $data) = @_;
    $log->debugf("deserializing %s with %s",Dumper($data), $type);
        
    if ($type eq 'DateTime') {
        return DateTime->from_epoch(epoch => str2time($data));
    } elsif ( grep( /^$type$/, ('int', 'double', 'string', 'boolean'))) {
        return $data;
    } else { # hash(model)
        my $_instance = eval "WWW::OpenAPIClient::Object::$type->new()";
        return $_instance->from_hash($data);
    }
}



__PACKAGE__->class_documentation({description => 'The response will be a JSON object.',
                                  class => 'GeolocationResponseSchema',
                                  required => [], # TODO
}                                 );

__PACKAGE__->method_documentation({
    'status' => {
    	datatype => 'string',
    	base_name => 'status',
    	description => 'If the request is successful, ok is returned. Otherwise error is returned',
    	format => '',
    	read_only => '',
    		},
    'message' => {
    	datatype => 'string',
    	base_name => 'message',
    	description => 'Any additional information from the server is returned here',
    	format => '',
    	read_only => '',
    		},
    'balance' => {
    	datatype => 'int',
    	base_name => 'balance',
    	description => 'This represents the remaining balance on the API token. Requests that return error are not charged and do not affect balance',
    	format => '',
    	read_only => '',
    		},
    'balance_slots' => {
    	datatype => 'int',
    	base_name => 'balance_slots',
    	description => 'This represents the remaining balance of device slots. Requests that return error are not charged and do not affect balance. If -1 is returned, then observe it as an error while calculating slots balance. This element will only exist if you are on a device plan.',
    	format => '',
    	read_only => '',
    		},
    'lat' => {
    	datatype => 'double',
    	base_name => 'lat',
    	description => 'The latitude representing the location',
    	format => '',
    	read_only => '',
    		},
    'lon' => {
    	datatype => 'double',
    	base_name => 'lon',
    	description => 'The longitude representing the location',
    	format => '',
    	read_only => '',
    		},
    'accuracy' => {
    	datatype => 'int',
    	base_name => 'accuracy',
    	description => 'The accuracy of the position is returned in meters',
    	format => '',
    	read_only => '',
    		},
    'address' => {
    	datatype => 'string',
    	base_name => 'address',
    	description => 'The physical address of the location',
    	format => '',
    	read_only => '',
    		},
    'address_details' => {
    	datatype => 'AddressDetailsSchema',
    	base_name => 'address_details',
    	description => '',
    	format => '',
    	read_only => '',
    		},
    'aged' => {
    	datatype => 'int',
    	base_name => 'aged',
    	description => 'Shown when the location is based on a single measurement or those older than 90 days or is an LAC fallback',
    	format => '',
    	read_only => '',
    		},
    'fallback' => {
    	datatype => 'FallbackSchema',
    	base_name => 'fallback',
    	description => '',
    	format => '',
    	read_only => '',
    		},
});

__PACKAGE__->openapi_types( {
    'status' => 'string',
    'message' => 'string',
    'balance' => 'int',
    'balance_slots' => 'int',
    'lat' => 'double',
    'lon' => 'double',
    'accuracy' => 'int',
    'address' => 'string',
    'address_details' => 'AddressDetailsSchema',
    'aged' => 'int',
    'fallback' => 'FallbackSchema'
} );

__PACKAGE__->attribute_map( {
    'status' => 'status',
    'message' => 'message',
    'balance' => 'balance',
    'balance_slots' => 'balance_slots',
    'lat' => 'lat',
    'lon' => 'lon',
    'accuracy' => 'accuracy',
    'address' => 'address',
    'address_details' => 'address_details',
    'aged' => 'aged',
    'fallback' => 'fallback'
} );

__PACKAGE__->mk_accessors(keys %{__PACKAGE__->attribute_map});


1;
