=begin
#Location API

#Geolocation, Geocoding and Maps

OpenAPI spec version: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for unwiredClient::REVERSEApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'REVERSEApi' do
  before do
    # run before each test
    @instance = unwiredClient::REVERSEApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of REVERSEApi' do
    it 'should create an instance of REVERSEApi' do
      expect(@instance).to be_instance_of(unwiredClient::REVERSEApi)
    end
  end

  # unit tests for reverse
  # Reverse Geocoding
  # Reverse geocoding is the process of converting a coordinate or location (latitude, longitude) to a readable address or place name. This permits the identification of nearby street addresses, places, and/or area subdivisions such as a neighborhood, county, state, or country.
  # @param lat Latitude of the location to generate an address for.
  # @param lon Longitude of the location to generate an address for.
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :zoom Zoom value lies between 0-18. Level of detail required where 0 is country and 18 is house/building
  # @option opts [String] :accept_language Preferred language order for showing search results, overrides the value specified in the Accept-Language HTTP header. Defaults to en. To use native language for the response when available, use accept-language&#x3D;native
  # @return [Object]
  describe 'reverse test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
