=begin
#Location API

#Geolocation, Geocoding and Maps

OpenAPI spec version: 2.0.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 3.3.4

=end

require 'spec_helper'
require 'json'

# Unit tests for unwiredClient::TimezoneApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TimezoneApi' do
  before do
    # run before each test
    @instance = unwiredClient::TimezoneApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TimezoneApi' do
    it 'should create an instance of TimezoneApi' do
      expect(@instance).to be_instance_of(unwiredClient::TimezoneApi)
    end
  end

  # unit tests for timezone
  # timezone
  # The Unwired Labs TimeZone API provides time offset data for locations on the surface of the earth.
  # @param lat lattitude of the location
  # @param lon longitude of location
  # @param [Hash] opts the optional parameters
  # @return [Object]
  describe 'timezone test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
