/* 
 * Location API
 *
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = unwired.Client.OpenAPIDateConverter;

namespace unwired.Model
{
    /// <summary>
    /// Radio type of the device. Supported values are ‘gsm’, ‘cdma’, ‘umts’ and ‘lte’. This field should be included for more accurate results.
    /// </summary>
    /// <value>Radio type of the device. Supported values are ‘gsm’, ‘cdma’, ‘umts’ and ‘lte’. This field should be included for more accurate results.</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum RadioSchema
    {
        /// <summary>
        /// Enum Gsm for value: \"gsm\"
        /// </summary>
        [EnumMember(Value = "\"gsm\"")]
        Gsm = 1,

        /// <summary>
        /// Enum Utms for value: \"utms\"
        /// </summary>
        [EnumMember(Value = "\"utms\"")]
        Utms = 2,

        /// <summary>
        /// Enum Cdma for value: \"cdma\"
        /// </summary>
        [EnumMember(Value = "\"cdma\"")]
        Cdma = 3,

        /// <summary>
        /// Enum Lte for value: \"lte\"
        /// </summary>
        [EnumMember(Value = "\"lte\"")]
        Lte = 4

    }

}
