# coding: utf-8

"""
    Location API

    Geolocation, Geocoding and Maps  # noqa: E501

    OpenAPI spec version: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import unwired
from unwired.models.geolocation_address_schema import GeolocationAddressSchema  # noqa: E501
from unwired.rest import ApiException


class TestGeolocationAddressSchema(unittest.TestCase):
    """GeolocationAddressSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGeolocationAddressSchema(self):
        """Test GeolocationAddressSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = unwired.models.geolocation_address_schema.GeolocationAddressSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
