# coding: utf-8

"""
    Location API

    Geolocation, Geocoding and Maps  # noqa: E501

    OpenAPI spec version: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import unwired
from unwired.api.geolocation_api import GEOLOCATIONApi  # noqa: E501
from unwired.rest import ApiException


class TestGEOLOCATIONApi(unittest.TestCase):
    """GEOLOCATIONApi unit test stubs"""

    def setUp(self):
        self.api = unwired.api.geolocation_api.GEOLOCATIONApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_geolocation(self):
        """Test case for geolocation

        Geolocation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
