# coding: utf-8

"""
    Location API

    Geolocation, Geocoding and Maps  # noqa: E501

    OpenAPI spec version: 2.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import unwired
from unwired.models.bt_schema import BtSchema  # noqa: E501
from unwired.rest import ApiException


class TestBtSchema(unittest.TestCase):
    """BtSchema unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBtSchema(self):
        """Test BtSchema"""
        # FIXME: construct object with mandatory attributes with example values
        # model = unwired.models.bt_schema.BtSchema()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
