//
// BalanceResponseSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct BalanceResponseSchema: Codable {

    /** If the request is successful, ok is returned. Otherwise error is returned */
    public var status: String?
    /** Remaining balance left in the account for geolocation requests */
    public var balanceGeolocation: Int64?
    /** Remaining balance left in the account for geocoding requests */
    public var balanceGeocoding: Int64?

    public init(status: String?, balanceGeolocation: Int64?, balanceGeocoding: Int64?) {
        self.status = status
        self.balanceGeolocation = balanceGeolocation
        self.balanceGeocoding = balanceGeocoding
    }

    public enum CodingKeys: String, CodingKey { 
        case status
        case balanceGeolocation = "balance_geolocation"
        case balanceGeocoding = "balance_geocoding"
    }


}

