//
// BtSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Specify level of strictness to apply to Borders */
public enum BtSchema: Int, Codable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
