//
// ErrorSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ErrorSchema: Codable {

    /** If the request is successful, ok is returned. Otherwise error is returned */
    public var status: String?
    /** Any additional information from the server is returned here */
    public var message: String?

    public init(status: String?, message: String?) {
        self.status = status
        self.message = message
    }


}

