//
// GeolocationAddressSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** The physical address of the returned location */
public enum GeolocationAddressSchema: Int64, Codable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
