//
// IpfSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Enable IP address fallback. Specify IP address of the device in the “ip” field if it’s different from the device making the API call. */
public enum IpfSchema: Int, Codable {
    case _0 = 0
    case _1 = 1
}
