//
// LacfSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Enable LAC fallback. If we are unable to locate a cell, we will return an approzimate location based on nearby cells in our database. */
public enum LacfSchema: Int, Codable {
    case _0 = 0
    case _1 = 1
    case _2 = 2
}
