//
// RadioSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Radio type of the device. Supported values are ‘gsm’, ‘cdma’, ‘umts’ and ‘lte’. This field should be included for more accurate results. */
public enum RadioSchema: String, Codable {
    case gsm&quot; = ""gsm""
    case utms&quot; = ""utms""
    case cdma&quot; = ""cdma""
    case lte&quot; = ""lte""
}
