//
// ReverseResponseSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct ReverseResponseSchema: Codable {

    /** If the request is successful, ok is returned. Otherwise error is returned */
    public var status: String?
    /** Balance left in the account */
    public var balance: Int64?
    public var address: AddressSchema?

    public init(status: String?, balance: Int64?, address: AddressSchema?) {
        self.status = status
        self.balance = balance
        self.address = address
    }


}

