//
// ScfSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Enable Short CID fallback. Adds support for devices that can only see 16-bit (short) CID of an UMTS 28-bit UTRAN CID. */
public enum ScfSchema: Int, Codable {
    case _0 = 0
    case _1 = 1
}
