//
// TimezoneSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


/** Timezone object found for the location. */

public struct TimezoneSchema: Codable {

    /** Short name of the Timezone */
    public var shortName: String?
    /** The offset from UTC (in seconds) for the given location. Considers DST savings. */
    public var offsetSec: Double?
    /** Represents whether the zone currently observing DST or not */
    public var nowInDst: String?
    /** Timezone name of the Location */
    public var name: String?

    public init(shortName: String?, offsetSec: Double?, nowInDst: String?, name: String?) {
        self.shortName = shortName
        self.offsetSec = offsetSec
        self.nowInDst = nowInDst
        self.name = name
    }

    public enum CodingKeys: String, CodingKey { 
        case shortName = "short_name"
        case offsetSec = "offset_sec"
        case nowInDst = "now_in_dst"
        case name
    }


}

