//
// TimezoneResponseSchema.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



public struct TimezoneResponseSchema: Codable {

    /** If the request is successful, ok is returned. Otherwise error is returned */
    public var status: String?
    /** Balance left in the account */
    public var balance: Int64?
    public var timezone: TimezoneSchema?

    public init(status: String?, balance: Int64?, timezone: TimezoneSchema?) {
        self.status = status
        self.balance = balance
        self.timezone = timezone
    }


}

