/*
 * Location API
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.unwired.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Address object found for the search query
 */
@ApiModel(description = "Address object found for the search query")

public class AddressSchema {
  public static final String SERIALIZED_NAME_LAT = "lat";
  @SerializedName(SERIALIZED_NAME_LAT)
  private String lat;

  public static final String SERIALIZED_NAME_LON = "lon";
  @SerializedName(SERIALIZED_NAME_LON)
  private String lon;

  public static final String SERIALIZED_NAME_DISPLAY_NAME = "display_name";
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;

  public static final String SERIALIZED_NAME_HOUSE_NUMBER = "house_number";
  @SerializedName(SERIALIZED_NAME_HOUSE_NUMBER)
  private String houseNumber;

  public static final String SERIALIZED_NAME_ROAD = "road";
  @SerializedName(SERIALIZED_NAME_ROAD)
  private String road;

  public static final String SERIALIZED_NAME_NEIGHBORHOOD = "neighborhood";
  @SerializedName(SERIALIZED_NAME_NEIGHBORHOOD)
  private String neighborhood;

  public static final String SERIALIZED_NAME_SUBURB = "suburb";
  @SerializedName(SERIALIZED_NAME_SUBURB)
  private String suburb;

  public static final String SERIALIZED_NAME_CITY = "city";
  @SerializedName(SERIALIZED_NAME_CITY)
  private String city;

  public static final String SERIALIZED_NAME_COUNTY = "county";
  @SerializedName(SERIALIZED_NAME_COUNTY)
  private String county;

  public static final String SERIALIZED_NAME_COUNTRY = "country";
  @SerializedName(SERIALIZED_NAME_COUNTRY)
  private String country;

  public static final String SERIALIZED_NAME_COUNTRY_CODE = "country_code";
  @SerializedName(SERIALIZED_NAME_COUNTRY_CODE)
  private String countryCode;

  public static final String SERIALIZED_NAME_POSTAL_CODE = "postal_code";
  @SerializedName(SERIALIZED_NAME_POSTAL_CODE)
  private String postalCode;

  public AddressSchema lat(String lat) {
    this.lat = lat;
    return this;
  }

   /**
   * Latitude of the given location (decimal)
   * @return lat
  **/
  @ApiModelProperty(example = "\"41.3438648\"", value = "Latitude of the given location (decimal)")
  public String getLat() {
    return lat;
  }

  public void setLat(String lat) {
    this.lat = lat;
  }

  public AddressSchema lon(String lon) {
    this.lon = lon;
    return this;
  }

   /**
   * Longitude of the given location (decimal)
   * @return lon
  **/
  @ApiModelProperty(example = "\"-86.3111653\"", value = "Longitude of the given location (decimal)")
  public String getLon() {
    return lon;
  }

  public void setLon(String lon) {
    this.lon = lon;
  }

  public AddressSchema displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

   /**
   * Matched Address name for the given location
   * @return displayName
  **/
  @ApiModelProperty(example = "\"Southpark Lane, Littleton,Arapahoe county, colorado, 800\"", value = "Matched Address name for the given location")
  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public AddressSchema houseNumber(String houseNumber) {
    this.houseNumber = houseNumber;
    return this;
  }

   /**
   * House Number
   * @return houseNumber
  **/
  @ApiModelProperty(value = "House Number")
  public String getHouseNumber() {
    return houseNumber;
  }

  public void setHouseNumber(String houseNumber) {
    this.houseNumber = houseNumber;
  }

  public AddressSchema road(String road) {
    this.road = road;
    return this;
  }

   /**
   * Road Name
   * @return road
  **/
  @ApiModelProperty(example = "\"Southpark Lane\"", value = "Road Name")
  public String getRoad() {
    return road;
  }

  public void setRoad(String road) {
    this.road = road;
  }

  public AddressSchema neighborhood(String neighborhood) {
    this.neighborhood = neighborhood;
    return this;
  }

   /**
   * Neighbourhood
   * @return neighborhood
  **/
  @ApiModelProperty(value = "Neighbourhood")
  public String getNeighborhood() {
    return neighborhood;
  }

  public void setNeighborhood(String neighborhood) {
    this.neighborhood = neighborhood;
  }

  public AddressSchema suburb(String suburb) {
    this.suburb = suburb;
    return this;
  }

   /**
   * Suburb
   * @return suburb
  **/
  @ApiModelProperty(value = "Suburb")
  public String getSuburb() {
    return suburb;
  }

  public void setSuburb(String suburb) {
    this.suburb = suburb;
  }

  public AddressSchema city(String city) {
    this.city = city;
    return this;
  }

   /**
   * City name (normalized form of city, town, village, hamlet)
   * @return city
  **/
  @ApiModelProperty(example = "\"Denver-Aurora-Lakewood\"", value = "City name (normalized form of city, town, village, hamlet)")
  public String getCity() {
    return city;
  }

  public void setCity(String city) {
    this.city = city;
  }

  public AddressSchema county(String county) {
    this.county = county;
    return this;
  }

   /**
   * County name (normalized form of county, state_district)
   * @return county
  **/
  @ApiModelProperty(value = "County name (normalized form of county, state_district)")
  public String getCounty() {
    return county;
  }

  public void setCounty(String county) {
    this.county = county;
  }

  public AddressSchema country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Country name
   * @return country
  **/
  @ApiModelProperty(example = "\"United States of america\"", value = "Country name")
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public AddressSchema countryCode(String countryCode) {
    this.countryCode = countryCode;
    return this;
  }

   /**
   * Country code
   * @return countryCode
  **/
  @ApiModelProperty(example = "\"US\"", value = "Country code")
  public String getCountryCode() {
    return countryCode;
  }

  public void setCountryCode(String countryCode) {
    this.countryCode = countryCode;
  }

  public AddressSchema postalCode(String postalCode) {
    this.postalCode = postalCode;
    return this;
  }

   /**
   * Postal code
   * @return postalCode
  **/
  @ApiModelProperty(example = "\"80120\"", value = "Postal code")
  public String getPostalCode() {
    return postalCode;
  }

  public void setPostalCode(String postalCode) {
    this.postalCode = postalCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AddressSchema addressSchema = (AddressSchema) o;
    return Objects.equals(this.lat, addressSchema.lat) &&
        Objects.equals(this.lon, addressSchema.lon) &&
        Objects.equals(this.displayName, addressSchema.displayName) &&
        Objects.equals(this.houseNumber, addressSchema.houseNumber) &&
        Objects.equals(this.road, addressSchema.road) &&
        Objects.equals(this.neighborhood, addressSchema.neighborhood) &&
        Objects.equals(this.suburb, addressSchema.suburb) &&
        Objects.equals(this.city, addressSchema.city) &&
        Objects.equals(this.county, addressSchema.county) &&
        Objects.equals(this.country, addressSchema.country) &&
        Objects.equals(this.countryCode, addressSchema.countryCode) &&
        Objects.equals(this.postalCode, addressSchema.postalCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(lat, lon, displayName, houseNumber, road, neighborhood, suburb, city, county, country, countryCode, postalCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AddressSchema {\n");
    
    sb.append("    lat: ").append(toIndentedString(lat)).append("\n");
    sb.append("    lon: ").append(toIndentedString(lon)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    houseNumber: ").append(toIndentedString(houseNumber)).append("\n");
    sb.append("    road: ").append(toIndentedString(road)).append("\n");
    sb.append("    neighborhood: ").append(toIndentedString(neighborhood)).append("\n");
    sb.append("    suburb: ").append(toIndentedString(suburb)).append("\n");
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    county: ").append(toIndentedString(county)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    countryCode: ").append(toIndentedString(countryCode)).append("\n");
    sb.append("    postalCode: ").append(toIndentedString(postalCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

