/*
 * Location API
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.unwired.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * GeolocationErrorSchema
 */

public class GeolocationErrorSchema {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_BALANCE = "balance";
  @SerializedName(SERIALIZED_NAME_BALANCE)
  private Long balance;

  public GeolocationErrorSchema status(String status) {
    this.status = status;
    return this;
  }

   /**
   * If the request is successful, ok is returned. Otherwise error is returned
   * @return status
  **/
  @ApiModelProperty(example = "error", value = "If the request is successful, ok is returned. Otherwise error is returned")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public GeolocationErrorSchema message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Any additional information from the server is returned here
   * @return message
  **/
  @ApiModelProperty(example = "INVALID_TOKEN", value = "Any additional information from the server is returned here")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public GeolocationErrorSchema balance(Long balance) {
    this.balance = balance;
    return this;
  }

   /**
   * This represents the remaining balance on the API token. Requests that return error are not charged and do not affect balance.
   * @return balance
  **/
  @ApiModelProperty(example = "0", value = "This represents the remaining balance on the API token. Requests that return error are not charged and do not affect balance.")
  public Long getBalance() {
    return balance;
  }

  public void setBalance(Long balance) {
    this.balance = balance;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeolocationErrorSchema geolocationErrorSchema = (GeolocationErrorSchema) o;
    return Objects.equals(this.status, geolocationErrorSchema.status) &&
        Objects.equals(this.message, geolocationErrorSchema.message) &&
        Objects.equals(this.balance, geolocationErrorSchema.balance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, message, balance);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeolocationErrorSchema {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

