/*
 * Location API
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.unwired.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.unwired.client.model.AddressSchema;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

/**
 * SearchResponseSchema
 */

public class SearchResponseSchema {
  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;

  public static final String SERIALIZED_NAME_BALANCE = "balance";
  @SerializedName(SERIALIZED_NAME_BALANCE)
  private BigDecimal balance;

  public static final String SERIALIZED_NAME_ADDRESSES = "addresses";
  @SerializedName(SERIALIZED_NAME_ADDRESSES)
  private List<AddressSchema> addresses = null;

  public SearchResponseSchema status(String status) {
    this.status = status;
    return this;
  }

   /**
   * If the request is successful, ok is returned. Otherwise error is returned
   * @return status
  **/
  @ApiModelProperty(example = "error", value = "If the request is successful, ok is returned. Otherwise error is returned")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public SearchResponseSchema balance(BigDecimal balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Balance left in the account
   * @return balance
  **/
  @ApiModelProperty(example = "0", value = "Balance left in the account")
  public BigDecimal getBalance() {
    return balance;
  }

  public void setBalance(BigDecimal balance) {
    this.balance = balance;
  }

  public SearchResponseSchema addresses(List<AddressSchema> addresses) {
    this.addresses = addresses;
    return this;
  }

  public SearchResponseSchema addAddressesItem(AddressSchema addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<AddressSchema>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * Array of Address objects found for the search query
   * @return addresses
  **/
  @ApiModelProperty(value = "Array of Address objects found for the search query")
  public List<AddressSchema> getAddresses() {
    return addresses;
  }

  public void setAddresses(List<AddressSchema> addresses) {
    this.addresses = addresses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SearchResponseSchema searchResponseSchema = (SearchResponseSchema) o;
    return Objects.equals(this.status, searchResponseSchema.status) &&
        Objects.equals(this.balance, searchResponseSchema.balance) &&
        Objects.equals(this.addresses, searchResponseSchema.addresses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, balance, addresses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SearchResponseSchema {\n");
    
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

