# Location API
#
# Geolocation, Geocoding and Maps
#
# OpenAPI spec version: 2.0.0
# 
# Generated by: https://openapi-generator.tech


#' CellSchema Class
#'
#' @field lac 
#' @field cid 
#' @field radio 
#' @field mcc mcc
#' @field mnc mnc
#' @field signal 
#' @field psc 
#' @field asu 
#' @field ta 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CellSchema <- R6::R6Class(
  'CellSchema',
  public = list(
    `lac` = NULL,
    `cid` = NULL,
    `radio` = NULL,
    `mcc` = NULL,
    `mnc` = NULL,
    `signal` = NULL,
    `psc` = NULL,
    `asu` = NULL,
    `ta` = NULL,
    initialize = function(`lac`, `cid`, `radio`, `mcc`, `mnc`, `signal`, `psc`, `asu`, `ta`){
      if (!missing(`lac`)) {
        stopifnot(is.numeric(`lac`), length(`lac`) == 1)
        self$`lac` <- `lac`
      }
      if (!missing(`cid`)) {
        stopifnot(is.numeric(`cid`), length(`cid`) == 1)
        self$`cid` <- `cid`
      }
      if (!missing(`radio`)) {
        stopifnot(R6::is.R6(`radio`))
        self$`radio` <- `radio`
      }
      if (!missing(`mcc`)) {
        stopifnot(is.numeric(`mcc`), length(`mcc`) == 1)
        self$`mcc` <- `mcc`
      }
      if (!missing(`mnc`)) {
        stopifnot(is.numeric(`mnc`), length(`mnc`) == 1)
        self$`mnc` <- `mnc`
      }
      if (!missing(`signal`)) {
        stopifnot(is.numeric(`signal`), length(`signal`) == 1)
        self$`signal` <- `signal`
      }
      if (!missing(`psc`)) {
        stopifnot(is.numeric(`psc`), length(`psc`) == 1)
        self$`psc` <- `psc`
      }
      if (!missing(`asu`)) {
        stopifnot(is.numeric(`asu`), length(`asu`) == 1)
        self$`asu` <- `asu`
      }
      if (!missing(`ta`)) {
        stopifnot(is.numeric(`ta`), length(`ta`) == 1)
        self$`ta` <- `ta`
      }
    },
    toJSON = function() {
      CellSchemaObject <- list()
      if (!is.null(self$`lac`)) {
        CellSchemaObject[['lac']] <- self$`lac`
      }
      if (!is.null(self$`cid`)) {
        CellSchemaObject[['cid']] <- self$`cid`
      }
      if (!is.null(self$`radio`)) {
        CellSchemaObject[['radio']] <- self$`radio`$toJSON()
      }
      if (!is.null(self$`mcc`)) {
        CellSchemaObject[['mcc']] <- self$`mcc`
      }
      if (!is.null(self$`mnc`)) {
        CellSchemaObject[['mnc']] <- self$`mnc`
      }
      if (!is.null(self$`signal`)) {
        CellSchemaObject[['signal']] <- self$`signal`
      }
      if (!is.null(self$`psc`)) {
        CellSchemaObject[['psc']] <- self$`psc`
      }
      if (!is.null(self$`asu`)) {
        CellSchemaObject[['asu']] <- self$`asu`
      }
      if (!is.null(self$`ta`)) {
        CellSchemaObject[['ta']] <- self$`ta`
      }

      CellSchemaObject
    },
    fromJSON = function(CellSchemaJson) {
      CellSchemaObject <- jsonlite::fromJSON(CellSchemaJson)
      if (!is.null(CellSchemaObject$`lac`)) {
        self$`lac` <- CellSchemaObject$`lac`
      }
      if (!is.null(CellSchemaObject$`cid`)) {
        self$`cid` <- CellSchemaObject$`cid`
      }
      if (!is.null(CellSchemaObject$`radio`)) {
        radioObject <- RadioSchema$new()
        radioObject$fromJSON(jsonlite::toJSON(CellSchemaObject$radio, auto_unbox = TRUE))
        self$`radio` <- radioObject
      }
      if (!is.null(CellSchemaObject$`mcc`)) {
        self$`mcc` <- CellSchemaObject$`mcc`
      }
      if (!is.null(CellSchemaObject$`mnc`)) {
        self$`mnc` <- CellSchemaObject$`mnc`
      }
      if (!is.null(CellSchemaObject$`signal`)) {
        self$`signal` <- CellSchemaObject$`signal`
      }
      if (!is.null(CellSchemaObject$`psc`)) {
        self$`psc` <- CellSchemaObject$`psc`
      }
      if (!is.null(CellSchemaObject$`asu`)) {
        self$`asu` <- CellSchemaObject$`asu`
      }
      if (!is.null(CellSchemaObject$`ta`)) {
        self$`ta` <- CellSchemaObject$`ta`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "lac": %d,
           "cid": %d,
           "radio": %s,
           "mcc": %d,
           "mnc": %d,
           "signal": %d,
           "psc": %d,
           "asu": %d,
           "ta": %d
        }',
        self$`lac`,
        self$`cid`,
        self$`radio`$toJSON(),
        self$`mcc`,
        self$`mnc`,
        self$`signal`,
        self$`psc`,
        self$`asu`,
        self$`ta`
      )
    },
    fromJSONString = function(CellSchemaJson) {
      CellSchemaObject <- jsonlite::fromJSON(CellSchemaJson)
      self$`lac` <- CellSchemaObject$`lac`
      self$`cid` <- CellSchemaObject$`cid`
      RadioSchemaObject <- RadioSchema$new()
      self$`radio` <- RadioSchemaObject$fromJSON(jsonlite::toJSON(CellSchemaObject$radio, auto_unbox = TRUE))
      self$`mcc` <- CellSchemaObject$`mcc`
      self$`mnc` <- CellSchemaObject$`mnc`
      self$`signal` <- CellSchemaObject$`signal`
      self$`psc` <- CellSchemaObject$`psc`
      self$`asu` <- CellSchemaObject$`asu`
      self$`ta` <- CellSchemaObject$`ta`
    }
  )
)
