# Location API
#
# Geolocation, Geocoding and Maps
#
# OpenAPI spec version: 2.0.0
# 
# Generated by: https://openapi-generator.tech


#' ErrorSchema Class
#'
#' @field status status
#' @field message 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ErrorSchema <- R6::R6Class(
  'ErrorSchema',
  public = list(
    `status` = NULL,
    `message` = NULL,
    initialize = function(`status`, `message`){
      if (!missing(`status`)) {
        stopifnot(is.character(`status`), length(`status`) == 1)
        self$`status` <- `status`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      ErrorSchemaObject <- list()
      if (!is.null(self$`status`)) {
        ErrorSchemaObject[['status']] <- self$`status`
      }
      if (!is.null(self$`message`)) {
        ErrorSchemaObject[['message']] <- self$`message`
      }

      ErrorSchemaObject
    },
    fromJSON = function(ErrorSchemaJson) {
      ErrorSchemaObject <- jsonlite::fromJSON(ErrorSchemaJson)
      if (!is.null(ErrorSchemaObject$`status`)) {
        self$`status` <- ErrorSchemaObject$`status`
      }
      if (!is.null(ErrorSchemaObject$`message`)) {
        self$`message` <- ErrorSchemaObject$`message`
      }
    },
    toJSONString = function() {
       sprintf(
        '{
           "status": %s,
           "message": %s
        }',
        self$`status`,
        self$`message`
      )
    },
    fromJSONString = function(ErrorSchemaJson) {
      ErrorSchemaObject <- jsonlite::fromJSON(ErrorSchemaJson)
      self$`status` <- ErrorSchemaObject$`status`
      self$`message` <- ErrorSchemaObject$`message`
    }
  )
)
