# Location API
#
# Geolocation, Geocoding and Maps
#
# OpenAPI spec version: 2.0.0
# 
# Generated by: https://openapi-generator.tech


#' RadioSchema Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
RadioSchema <- R6::R6Class(
  'RadioSchema',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      RadioSchemaObject <- list()

      RadioSchemaObject
    },
    fromJSON = function(RadioSchemaJson) {
      RadioSchemaObject <- jsonlite::fromJSON(RadioSchemaJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(RadioSchemaJson) {
      RadioSchemaObject <- jsonlite::fromJSON(RadioSchemaJson)
    }
  )
)
