# Location API
#
# Geolocation, Geocoding and Maps
#
# OpenAPI spec version: 2.0.0
# 
# Generated by: https://openapi-generator.tech

#' @title REVERSE operations
#' @description unwired.REVERSE
#'
#' @field path Stores url path of the request.
#' @field apiClient Handles the client-server communication.
#' @field userAgent Set the user agent of the request.
#'
#' @importFrom R6 R6Class
#'
#' @section Methods:
#' \describe{
#'
#' reverse Reverse Geocoding
#'
#' }
#'
#' @export
REVERSEApi <- R6::R6Class(
  'REVERSEApi',
  public = list(
    userAgent = "OpenAPI-Generator/1.0.0/r",
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    reverse = function(lat, lon, zoom, accept_language, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- character()

      if (!missing(`lat`)) {
        queryParams['lat'] <- lat
      }

      if (!missing(`lon`)) {
        queryParams['lon'] <- lon
      }

      if (!missing(`zoom`)) {
        queryParams['zoom'] <- zoom
      }

      if (!missing(`accept_language`)) {
        queryParams['accept-language'] <- accept_language
      }

      urlPath <- "/reverse.php"
      resp <- self$apiClient$callApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)
      
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        returnObject <- object$new()
        result <- returnObject$fromJSON(httr::content(resp, "text", encoding = "UTF-8"))
        Response$new(returnObject, resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        Response$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        Response$new("API server error", resp)
      }

    }
  )
)
