# Location API
#
# Geolocation, Geocoding and Maps
#
# OpenAPI spec version: 2.0.0
# 
# Generated by: https://openapi-generator.tech


#' ScfSchema Class
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ScfSchema <- R6::R6Class(
  'ScfSchema',
  public = list(
    initialize = function(){
    },
    toJSON = function() {
      ScfSchemaObject <- list()

      ScfSchemaObject
    },
    fromJSON = function(ScfSchemaJson) {
      ScfSchemaObject <- jsonlite::fromJSON(ScfSchemaJson)
    },
    toJSONString = function() {
       sprintf(
        '{
        }',
      )
    },
    fromJSONString = function(ScfSchemaJson) {
      ScfSchemaObject <- jsonlite::fromJSON(ScfSchemaJson)
    }
  )
)
