<?php
/**
 * CellSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  unwired
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Location API
 *
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace unwired;

/**
 * CellSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description You can send 1 to 7 cell ID objects. If your device supports scanning for more than 7 cell objects, reach out to us and we’ll increase this limit on your account. The first cell object has to be that of the serving cell, i.e. the tower the device is connected to. The others are neighbouring cell objects that are visible to the device. Except lac and cid all other parameters mentioned below are optional. Parameters vary depending on the radio type. Supported radio types and their corresponding parameters are
 * @package     unwired
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CellSchemaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CellSchema"
     */
    public function testCellSchema()
    {
    }

    /**
     * Test attribute "lac"
     */
    public function testPropertyLac()
    {
    }

    /**
     * Test attribute "cid"
     */
    public function testPropertyCid()
    {
    }

    /**
     * Test attribute "radio"
     */
    public function testPropertyRadio()
    {
    }

    /**
     * Test attribute "mcc"
     */
    public function testPropertyMcc()
    {
    }

    /**
     * Test attribute "mnc"
     */
    public function testPropertyMnc()
    {
    }

    /**
     * Test attribute "signal"
     */
    public function testPropertySignal()
    {
    }

    /**
     * Test attribute "psc"
     */
    public function testPropertyPsc()
    {
    }

    /**
     * Test attribute "asu"
     */
    public function testPropertyAsu()
    {
    }

    /**
     * Test attribute "ta"
     */
    public function testPropertyTa()
    {
    }
}
