<?php
/**
 * GeolocationSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  unwired
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Location API
 *
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace unwired;

/**
 * GeolocationSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description GeolocationSchema
 * @package     unwired
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class GeolocationSchemaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "GeolocationSchema"
     */
    public function testGeolocationSchema()
    {
    }

    /**
     * Test attribute "token"
     */
    public function testPropertyToken()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "radio"
     */
    public function testPropertyRadio()
    {
    }

    /**
     * Test attribute "mcc"
     */
    public function testPropertyMcc()
    {
    }

    /**
     * Test attribute "mnc"
     */
    public function testPropertyMnc()
    {
    }

    /**
     * Test attribute "cells"
     */
    public function testPropertyCells()
    {
    }

    /**
     * Test attribute "wifi"
     */
    public function testPropertyWifi()
    {
    }

    /**
     * Test attribute "fallbacks"
     */
    public function testPropertyFallbacks()
    {
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
    }

    /**
     * Test attribute "ip"
     */
    public function testPropertyIp()
    {
    }

    /**
     * Test attribute "bt"
     */
    public function testPropertyBt()
    {
    }
}
