<?php
/**
 * LacfSchemaTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  unwired
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Location API
 *
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 3.3.4
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace unwired;

/**
 * LacfSchemaTest Class Doc Comment
 *
 * @category    Class
 * @description Enable LAC fallback. If we are unable to locate a cell, we will return an approzimate location based on nearby cells in our database.
 * @package     unwired
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class LacfSchemaTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "LacfSchema"
     */
    public function testLacfSchema()
    {
    }
}
