/* 
 * Location API
 *
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use std::rc::Rc;
use std::borrow::Borrow;

use hyper;
use serde_json;
use futures::Future;

use super::{Error, configuration};
use super::request as __internal_request;

pub struct REVERSEApiClient<C: hyper::client::Connect> {
    configuration: Rc<configuration::Configuration<C>>,
}

impl<C: hyper::client::Connect> REVERSEApiClient<C> {
    pub fn new(configuration: Rc<configuration::Configuration<C>>) -> REVERSEApiClient<C> {
        REVERSEApiClient {
            configuration: configuration,
        }
    }
}

pub trait REVERSEApi {
    fn reverse(&self, lat: f64, lon: f64, zoom: i64, accept_language: &str) -> Box<Future<Item = Value, Error = Error<serde_json::Value>>>;
}


impl<C: hyper::client::Connect>REVERSEApi for REVERSEApiClient<C> {
    fn reverse(&self, lat: f64, lon: f64, zoom: i64, accept_language: &str) -> Box<Future<Item = Value, Error = Error<serde_json::Value>>> {
        __internal_request::Request::new(hyper::Method::Get, "/reverse.php".to_string())
            .with_auth(__internal_request::Auth::ApiKey(__internal_request::ApiKey{
                in_header: false,
                in_query: true,
                param_name: "token".to_owned(),
            }))
            .with_query_param("lat".to_string(), lat.to_string())
            .with_query_param("lon".to_string(), lon.to_string())
            .with_query_param("zoom".to_string(), zoom.to_string())
            .with_query_param("accept-language".to_string(), accept_language.to_string())
            .execute(self.configuration.borrow())
    }

}
