//
// GEOLOCATIONAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
import Alamofire



open class GEOLOCATIONAPI {
    /**
     Geolocation
     
     - parameter geolocationSchema: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func geolocation(geolocationSchema: GeolocationSchema, completion: @escaping ((_ data: Any?,_ error: Error?) -> Void)) {
        geolocationWithRequestBuilder(geolocationSchema: geolocationSchema).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Geolocation
     - POST /process.php
     - The Geolocation API helps developers locate IoT, M2M and other connected devices anywhere in the world without GPS. The device first sends the API data about which Cellular networks and WiFi networks it can see nearby. The API then uses Unwired Labs’ large datasets of Cell towers, WiFi networks backed by numerous algorithms to calculate and return the device’s location
     - parameter geolocationSchema: (body)  
     - returns: RequestBuilder<Any> 
     */
    open class func geolocationWithRequestBuilder(geolocationSchema: GeolocationSchema) -> RequestBuilder<Any> {
        let path = "/process.php"
        let URLString = unwiredAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: geolocationSchema)

        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<Any>.Type = unwiredAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
