/* 
 * Location API
 *
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using unwired.Api;
using unwired.Model;
using unwired.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace unwired.Test
{
    /// <summary>
    ///  Class for testing GeolocationAddressSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GeolocationAddressSchemaTests
    {
        // TODO uncomment below to declare an instance variable for GeolocationAddressSchema
        //private GeolocationAddressSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GeolocationAddressSchema
            //instance = new GeolocationAddressSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GeolocationAddressSchema
        /// </summary>
        [Test]
        public void GeolocationAddressSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GeolocationAddressSchema
            //Assert.IsInstanceOfType<GeolocationAddressSchema> (instance, "variable 'instance' is a GeolocationAddressSchema");
        }



    }

}
