/* 
 * Location API
 *
 * Geolocation, Geocoding and Maps
 *
 * OpenAPI spec version: 2.0.0
 * 
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using unwired.Api;
using unwired.Model;
using unwired.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace unwired.Test
{
    /// <summary>
    ///  Class for testing ReverseResponseSchema
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ReverseResponseSchemaTests
    {
        // TODO uncomment below to declare an instance variable for ReverseResponseSchema
        //private ReverseResponseSchema instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ReverseResponseSchema
            //instance = new ReverseResponseSchema();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ReverseResponseSchema
        /// </summary>
        [Test]
        public void ReverseResponseSchemaInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ReverseResponseSchema
            //Assert.IsInstanceOfType<ReverseResponseSchema> (instance, "variable 'instance' is a ReverseResponseSchema");
        }


        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Test]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Test]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }

    }

}
