/**
* Location API
* Geolocation, Geocoding and Maps
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package unwired.models

import unwired.models.AllSchema
import unwired.models.IpfSchema
import unwired.models.LacfSchema
import unwired.models.ScfSchema

/**
 * An array of fallback options to enable or disable.
 * @param all 
 * @param ipf 
 * @param lacf 
 * @param scf 
 */
data class FallbackSchema (
    val all: AllSchema? = null,
    val ipf: IpfSchema? = null,
    val lacf: LacfSchema? = null,
    val scf: ScfSchema? = null
) {

}

