/**
* Location API
* Geolocation, Geocoding and Maps
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package unwired.models

import unwired.models.BtSchema
import unwired.models.CellSchema
import unwired.models.FallbackSchema
import unwired.models.GeolocationAddressSchema
import unwired.models.RadioSchema
import unwired.models.WifiSchema

/**
 * 
 * @param token 
 * @param id ID of the device, in case you are in a per-device plan. This could be any unique string such as an IMEI, IMSI, phone number or a hash of any of the previous values, etc. Maximum accepted length is 20 chars, and values should only be alphanumeric (a-z, 0-9)
 * @param radio 
 * @param mcc \"Mobile Country Code of your operator’s network represented by an integer (Optional). Range: 0 to 999.\"
 * @param mnc Mobile Network Code of your operator’s network represented by an integer (Optional). Range: 0 to 999. On CDMA, provide the System ID or SID, with range: 1 to 32767.
 * @param cells An array of cell ID objects
 * @param wifi An array of WiFi objects visible to the device.
 * @param fallbacks 
 * @param address 
 * @param ip IP address of device.
 * @param bt 
 */
data class GeolocationSchema (
    val token: kotlin.String? = null,
    /* ID of the device, in case you are in a per-device plan. This could be any unique string such as an IMEI, IMSI, phone number or a hash of any of the previous values, etc. Maximum accepted length is 20 chars, and values should only be alphanumeric (a-z, 0-9) */
    val id: kotlin.String? = null,
    val radio: RadioSchema? = null,
    /* \"Mobile Country Code of your operator’s network represented by an integer (Optional). Range: 0 to 999.\" */
    val mcc: kotlin.Long? = null,
    /* Mobile Network Code of your operator’s network represented by an integer (Optional). Range: 0 to 999. On CDMA, provide the System ID or SID, with range: 1 to 32767. */
    val mnc: kotlin.Long? = null,
    /* An array of cell ID objects */
    val cells: kotlin.Array<CellSchema>? = null,
    /* An array of WiFi objects visible to the device. */
    val wifi: kotlin.Array<WifiSchema>? = null,
    val fallbacks: FallbackSchema? = null,
    val address: GeolocationAddressSchema? = null,
    /* IP address of device. */
    val ip: kotlin.String? = null,
    val bt: BtSchema? = null
) {

}

