/**
* Location API
* Geolocation, Geocoding and Maps
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package unwired.models


import com.squareup.moshi.Json

/**
* Radio type of the device. Supported values are ‘gsm’, ‘cdma’, ‘umts’ and ‘lte’. This field should be included for more accurate results.
* Values: gsmDoubleQuote,utmsDoubleQuote,cdmaDoubleQuote,lteDoubleQuote
*/
enum class RadioSchema(val value: kotlin.String){

    @Json(name = "\"gsm\"") gsmDoubleQuote("\"gsm\""),

    @Json(name = "\"utms\"") utmsDoubleQuote("\"utms\""),

    @Json(name = "\"cdma\"") cdmaDoubleQuote("\"cdma\""),

    @Json(name = "\"lte\"") lteDoubleQuote("\"lte\"");

}

