=begin comment

Location API

Geolocation, Geocoding and Maps

OpenAPI spec version: 2.0.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by the OpenAPI Generator
# Please update the test cases below to test the model.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 2;
use Test::Exception;

use lib 'lib';
use strict;
use warnings;


use_ok('WWW::OpenAPIClient::Object::GeolocationErrorSchema');

my $instance = WWW::OpenAPIClient::Object::GeolocationErrorSchema->new();

isa_ok($instance, 'WWW::OpenAPIClient::Object::GeolocationErrorSchema');

