=begin comment

Location API

Geolocation, Geocoding and Maps

OpenAPI spec version: 2.0.0

Generated by: https://openapi-generator.tech

=end comment

=cut

#
# NOTE: This class is auto generated by OpenAPI Generator
# Please update the test cases below to test the API endpoints.
# Ref: https://openapi-generator.tech
#
use Test::More tests => 1; #TODO update number of test cases
use Test::Exception;

use lib 'lib';
use strict;
use warnings;

use_ok('WWW::OpenAPIClient::REVERSEApi');

my $api = WWW::OpenAPIClient::REVERSEApi->new();
isa_ok($api, 'WWW::OpenAPIClient::REVERSEApi');

#
# reverse test
#
{
    my $lat = undef; # replace NULL with a proper value
    my $lon = undef; # replace NULL with a proper value
    my $zoom = undef; # replace NULL with a proper value
    my $accept_language = undef; # replace NULL with a proper value
    my $result = $api->reverse(lat => $lat, lon => $lon, zoom => $zoom, accept_language => $accept_language);
}


1;
