#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Location API
* Geolocation, Geocoding and Maps
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIRadioSchema.h"
@protocol OAIRadioSchema;
@class OAIRadioSchema;



@protocol OAICellSchema
@end

@interface OAICellSchema : OAIObject

/* the Location Area Code of your operator’s network. [optional]
 */
@property(nonatomic) NSNumber* lac;
/* Cell ID [optional]
 */
@property(nonatomic) NSNumber* cid;

@property(nonatomic) OAIRadioSchema* radio;
/* \"Mobile Country Code of your operator’s network represented by an integer (Optional). Range: 0 to 999.\" [optional]
 */
@property(nonatomic) NSNumber* mcc;
/* Mobile Network Code of your operator’s network represented by an integer (Optional). Range: 0 to 999. On CDMA, provide the System ID or SID, with range: 1 to 32767. [optional]
 */
@property(nonatomic) NSNumber* mnc;
/* Signal Strength (RSSI) [optional]
 */
@property(nonatomic) NSNumber* signal;
/* Primary Scrambling Code [optional]
 */
@property(nonatomic) NSNumber* psc;
/* Arbitrary Strength Unit [optional]
 */
@property(nonatomic) NSNumber* asu;
/* Timing Advance [optional]
 */
@property(nonatomic) NSNumber* ta;

@end
