#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Location API
* Geolocation, Geocoding and Maps
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/





@protocol OAIErrorSchema
@end

@interface OAIErrorSchema : OAIObject

/* If the request is successful, ok is returned. Otherwise error is returned [optional]
 */
@property(nonatomic) NSString* status;
/* Any additional information from the server is returned here [optional]
 */
@property(nonatomic) NSString* message;

@end
