#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Location API
* Geolocation, Geocoding and Maps
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAIBtSchema.h"
#import "OAICellSchema.h"
#import "OAIFallbackSchema.h"
#import "OAIGeolocationAddressSchema.h"
#import "OAIRadioSchema.h"
#import "OAIWifiSchema.h"
@protocol OAIBtSchema;
@class OAIBtSchema;
@protocol OAICellSchema;
@class OAICellSchema;
@protocol OAIFallbackSchema;
@class OAIFallbackSchema;
@protocol OAIGeolocationAddressSchema;
@class OAIGeolocationAddressSchema;
@protocol OAIRadioSchema;
@class OAIRadioSchema;
@protocol OAIWifiSchema;
@class OAIWifiSchema;



@protocol OAIGeolocationSchema
@end

@interface OAIGeolocationSchema : OAIObject


@property(nonatomic) NSString* token;
/* ID of the device, in case you are in a per-device plan. This could be any unique string such as an IMEI, IMSI, phone number or a hash of any of the previous values, etc. Maximum accepted length is 20 chars, and values should only be alphanumeric (a-z, 0-9) [optional]
 */
@property(nonatomic) NSString* _id;

@property(nonatomic) OAIRadioSchema* radio;
/* \"Mobile Country Code of your operator’s network represented by an integer (Optional). Range: 0 to 999.\" [optional]
 */
@property(nonatomic) NSNumber* mcc;
/* Mobile Network Code of your operator’s network represented by an integer (Optional). Range: 0 to 999. On CDMA, provide the System ID or SID, with range: 1 to 32767. [optional]
 */
@property(nonatomic) NSNumber* mnc;
/* An array of cell ID objects [optional]
 */
@property(nonatomic) NSArray<OAICellSchema>* cells;
/* An array of WiFi objects visible to the device. [optional]
 */
@property(nonatomic) NSArray<OAIWifiSchema>* wifi;

@property(nonatomic) OAIFallbackSchema* fallbacks;

@property(nonatomic) OAIGeolocationAddressSchema* address;
/* IP address of device. [optional]
 */
@property(nonatomic) NSString* ip;

@property(nonatomic) OAIBtSchema* bt;

@end
