#import <Foundation/Foundation.h>
#import "OAIObject.h"

/**
* Location API
* Geolocation, Geocoding and Maps
*
* OpenAPI spec version: 2.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/


#import "OAITimezoneSchema.h"
@protocol OAITimezoneSchema;
@class OAITimezoneSchema;



@protocol OAITimezoneResponseSchema
@end

@interface OAITimezoneResponseSchema : OAIObject

/* If the request is successful, ok is returned. Otherwise error is returned [optional]
 */
@property(nonatomic) NSString* status;
/* Balance left in the account [optional]
 */
@property(nonatomic) NSNumber* balance;

@property(nonatomic) OAITimezoneSchema* timezone;

@end
